#!/bin/bash
echo "Checking _authors file name structure (first_name.last_name.md)"
if ls _authors | grep --line-regexp --invert-match '[a-z_-]\+\.[a-z_-]\+\.md'; then
    cat <<EOF
One or more authors do not have the expected structure.
Notes:
A dot (.) can only appear as a separator between the first and the last names.
Dashes in names are kept as-is.
Spaces are replaced by underscores (_).
EOF
    exit 1
fi
