name: Diff the startups content

on:
  push: # tmp
    branches: ["*"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # every 1st day of month

jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run diff
        run: ./ci/git-analyser.sh -d ./content/_startups 30 out.md

      - name: Show diff
        run: cat out.md
